name: ExtraBows
version: 1.0
author: ketty64
main: me.ketty64.extrabows.Main
description: A plugin that adds custom bows to Minecraft.
api-version: 1.13
commands:
  extrabows:
    description: "Gives the player an extra bow."
    usage: "/extrabows <bow>"
    aliases:
      - eb
      - bow
    permission: extrabows.use
    permission-message: "You do not have permission to use this command."
permissions:
  extrabows.use:
    description: "Allows access to the /extrabows command."
    default: op
  extrabows.icebow:
    description: "Allows players to receive an IceBow."
    default: op
  extrabows.lightningbow:
    description: "Allows players to receive an LightningBow."
    default: op
  extrabows.explosivebow:
    description: "Allows players to receive an ExplosiveBow."
    default: op
  extrabows.teleportationbow:
    description: "Allows players to receive an TeleportationBow."
    default: op
  extrabows.grapplingbow:
    description: "Allows players to receive an GrappingBow."
    default: op
  extrabows.reload:
    description: "Allows players to reload the config file."
    default: op


